runtime: nodejs16
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: dist/client/\1
  upload: dist/client/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: dist/client/index.html
  upload: dist/client/index.html